spring.application.name=task-api

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Database initialization
spring.sql.init.mode=always

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html