spring.application.name=task-api

# Server Configuration
server.port=8080

# Show detailed error messages
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs